# Trigger word is case insensitive.
# Nickname can contain color codes using the '&' character.
triggerwords:
- chester
nickname: '<_Chester_>'
# The chat color will be the color chester talks in.
chatcolor: r
# If this is set to true, then operators will be notified if there is an update available for chester.
check-update: true